start ./Host/bin/Debug/netcoreapp3.1/Host.exe  "./DataStructures/host1.properties"
start ./Host/bin/Debug/netcoreapp3.1/Host.exe  "./DataStructures/host2.properties"
start ./Host/bin/Debug/netcoreapp3.1/Host.exe  "./DataStructures/host3.properties"
start ./Host/bin/Debug/netcoreapp3.1/Host.exe  "./DataStructures/host4.properties"
start ./CableCloud/bin/Debug/netcoreapp3.1/CableCloud.exe  "./DataStructures/CableCloud.properties"